services:
  web-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: desafio1-web-server
    ports:
      - "8080:8080"
    networks:
      - desafio1-network
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  web-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: desafio1-web-client
    networks:
      - desafio1-network
    depends_on:
      - web-server
    restart: unless-stopped

networks:
  desafio1-network:
    name: desafio1-network
    driver: bridge
